#### POS tagging + WordNet Lemmatization on a dataset column.

### Install and Download Required Resources

In [1]:
import nltk

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...

True

In [2]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [3]:
data = {
    "review":[
        "The boys are running in the park",
        "She was better at solving problems",
        "Students are learning machine learning"
    ]
}

df = pd.DataFrame(data)

In [4]:
df

                                   review
0        The boys are running in the park
1      She was better at solving problems
2  Students are learning machine learning

### Convert POS Tags to WordNet Format
- POS tags from nltk.pos_tag() are different from WordNet POS tags, so we convert them.

In [5]:
def get_wordnet_pos(tag):
    
    if tag.startswith('J'):
        return wordnet.ADJ
    
    elif tag.startswith('V'):
        return wordnet.VERB
    
    elif tag.startswith('N'):
        return wordnet.NOUN
    
    elif tag.startswith('R'):
        return wordnet.ADV
    
    else:
        return wordnet.NOUN

In [16]:
get_wordnet_pos("NN")

'n'

In [6]:
lemm = WordNetLemmatizer()

## Lemmatization Function

In [10]:
def lemmatize_text(text):
    
    tokens = nltk.word_tokenize(text)
    print("*******Tokens are : ",tokens)
    pos_tags = nltk.pos_tag(tokens)
    print("#######POS Tagging : ",pos_tags)
    lemmas = [
        lemm.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in pos_tags
    ]
    
    return " ".join(lemmas)

In [11]:
lemmatize_text("The boys are running in the park")

*******Tokens are :  ['The', 'boys', 'are', 'running', 'in', 'the', 'park']
#######POS Tagging :  [('The', 'DT'), ('boys', 'NNS'), ('are', 'VBP'), ('running', 'VBG'), ('in', 'IN'), ('the', 'DT'), ('park', 'NN')]

'The boy be run in the park'

In [14]:
lemm.lemmatize("are",pos="v")

'be'

## Apply on Dataset

In [9]:
df["clean_review"] = df["review"].apply(lemmatize_text)

df

                                   review                        clean_review
0        The boys are running in the park          The boy be run in the park
1      She was better at solving problems        She be good at solve problem
2  Students are learning machine learning  Students be learn machine learning